name: myfirstproject
description: A complete app with auth, weather, diary, and to-do list

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  google_fonts: ^6.2.1
  geolocator: ^11.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/profile.png
    - assets/images/  # <-- This line tells Flutter to include all files inside assets/images/
