// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjtmPYXgxw1MPRom0gE2pwx3vDCMnoUB8',
    appId: '1:389829924651:web:7230f84a6ff38cfa68576e',
    messagingSenderId: '389829924651',
    projectId: 'myfirstproject-51cf2',
    authDomain: 'myfirstproject-51cf2.firebaseapp.com',
    storageBucket: 'myfirstproject-51cf2.firebasestorage.app',
    measurementId: 'G-VZ922RZEV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaDX-DI6Kyui0WaojJXzBwDYh_Mkvoki0',
    appId: '1:389829924651:android:8b2cad072fc26d8668576e',
    messagingSenderId: '389829924651',
    projectId: 'myfirstproject-51cf2',
    storageBucket: 'myfirstproject-51cf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADN1FLFs8HVopG-O1EWs8Jg1I7T5uYiKU',
    appId: '1:389829924651:ios:6c7ab30fbb95584268576e',
    messagingSenderId: '389829924651',
    projectId: 'myfirstproject-51cf2',
    storageBucket: 'myfirstproject-51cf2.firebasestorage.app',
    iosClientId: '389829924651-5vtf9a463hqe6ne55eslapgofph6ebjt.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirstproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADN1FLFs8HVopG-O1EWs8Jg1I7T5uYiKU',
    appId: '1:389829924651:ios:6c7ab30fbb95584268576e',
    messagingSenderId: '389829924651',
    projectId: 'myfirstproject-51cf2',
    storageBucket: 'myfirstproject-51cf2.firebasestorage.app',
    iosClientId: '389829924651-5vtf9a463hqe6ne55eslapgofph6ebjt.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirstproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjtmPYXgxw1MPRom0gE2pwx3vDCMnoUB8',
    appId: '1:389829924651:web:45c8438a1a6d101568576e',
    messagingSenderId: '389829924651',
    projectId: 'myfirstproject-51cf2',
    authDomain: 'myfirstproject-51cf2.firebaseapp.com',
    storageBucket: 'myfirstproject-51cf2.firebasestorage.app',
    measurementId: 'G-8ME7XY95BN',
  );

}